config/routes.rb
Rails.application.routes.draw do

  namespace :student do
    get 'video_classes/index'
  end

  namespace :student do
    get 'video_classes/show'
  end

  get 'webinar/index'


  resources :events
  
  namespace :backend do
    resources :blogs
    get '/dashboard' => 'dashboard#index', :as => 'dashboard'
    resources :attitude, only: [:index, :show, :update]
    # get '/attitude' => 'attitude#index', :as => 'attitude'
    # resources :sections
    # resources :tasks
    # resources :schools
    # resources :careers
    # resources :universities
  end

  get 'student/courses' => 'student/courses#index', as: :user_root
  
  namespace :student do

    # ATTITUDE TESTS
    # post '/attitude/process' => 'attitude#process', :as => 'attitude_process'
    resources :attitude_tests, :path => "attitude", only: [:index, :show, :update]
    # resources :attitude_tests, :path => "attitude", only: [:index, :show] do
      # resources :course_user_tests, :path => "test", only:[:edit, :new, :update]
    # end
    
    resources :courses, only: [:index, :show] do
      # root_path
      
      # TESTS
      resources :tests, only: [:index] do
        resources :course_user_tests, :path => "test", only:[:edit, :new, :update]
      end
      
      # PROGRESS
      resources :progress, only: [:index] do
        # RESOURCES
        resources :resources, only: [:show, :update]
      end
      # LIVE CLASSES
      get '/live_classes' => 'live_classes#index'

      # QUESTIONS
      resources :categories do
        resources :sub_categories do
          resources :answers, only:[:create]
        end
      end

      # TUTORIALS
      resources :tutorials

      #STATISTICS
      resources :statistics, only: [:index]

     # TUTORIALS
      resources :video_classes

    end
    
  end

  # PAYMENTS
  get 'pagos' => 'payments#index', as: :payments

  root 'home#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # USERS
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'users/registrations', sessions: 'users/sessions' }

  # get 'auth/facebook/callback', to: 'sessions#create'
  # get 'auth/failure', to: redirect('/')
  
  match '*unmatched_route', :to => 'application#raise_not_found!', via: :all
end

app/controllers/student/answers_controller.rb
class Student::AnswersController < Student::StudentController
  before_filter :check_plan, only: [:index]
  before_action :set_data

  def create
    respond_to do |format|
      if !current_user.answers.where(answer_params).any?
        @answer = current_user.answers.new(answer_params)
        @answer.item = nil
        if @answer.save
          format.html { redirect_to student_course_category_sub_category_path(@course,@category,@sub_category), notice: 'La respuesta fue creada exitosamente.' }
          format.json { render json: { "is_correct": @answer.is_correct?, "already_answered": false }, status: :created }
        else
          format.html { redirect_to student_course_category_sub_category_path(@course,@category,@sub_category), notice: 'La respuesta no pudo ser creada.' }
          format.json { render json: @answer.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to student_course_category_sub_category_path(@course,@category,@sub_category), notice: 'La respuesta ya fue creada.' }
        format.json { render json: { "is_correct": false, "already_answered": true }, status: :unprocessable_entity }
      end
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:question_id, :choice_id)
  end

  def set_data
    @category = Category.find(params[:category_id])
    @sub_category = SubCategory.find(params[:sub_category_id])
    @course = Course.find(params[:course_id])
  end

end

app/controllers/student/attitude_tests_controller.rb
class Student::AttitudeTestsController < Student::StudentController
  before_action :load_uat, only: [:show]
  # before_action :update_tests_data
  before_filter :check_plan, only: [:show]

  def index
  end

  def update
    uat = current_user.user_attitude_tests.find_by_test_id(params[:id])
    Answer.where(item: uat).destroy_all if !uat.blank?
    qs = vs = []
    qs = params['question_ids'].keys.map { |e| e } if params['question_ids']
    vs = params['question_ids'].values.map { |e| e } if params['question_ids']
    us = current_user.slice(:id)
    i = qs.map.with_index { |e, k| k }
    data = []
    i.each do |i|
      data[i] = { 
                  "question_id" => qs[i].to_i, 
                  "choice_id"   => vs[i].to_i,
                  "user_id"     => current_user.id,
                  "item_id"     => uat.id,
                  "item_type"   => "UserAttitudeTest"
                }

    end
    
    band = false

    if params['action_form'] == "end" && current_user.user_attitude_tests.find_by_test_id(params[:id]).test.questions.count == vs.count
      current_user.user_attitude_tests.find_by_test_id(params[:id]).update_attribute(:status,1)
      band = true
    end

    if Answer.create!(data) and !data.blank?
      if params['action_form'] == "pause" && current_user.user_attitude_tests.find_by_test_id(params[:id]).test.questions.count >= vs.count
        return redirect_to student_attitude_test_path(params['id']), notice: 'Test pausado correctamente, para finalizar un test debe contestar todas las preguntas' 
      end
      if band
        return redirect_to student_courses_path, notice: 'Hemos recibido tus pruebas de actitud, muy pronto recibiras tu resultados por email' 
      else
        return redirect_to student_courses_path, notice: 'Test pausado, para finalizar un test debe contestar todas las preguntas' 
      end
    else
      return redirect_to student_attitude_test_path(params['id']), alert: 'Ocurrió un error al actualizar este test'
    end
  end
  
  def show
  end
  
  private
    
    def load_uat
      current_user.user_attitude_tests.create!(test_id: params[:id]) unless current_user.user_attitude_tests.find_by_test_id(params[:id])
      @uat = current_user.user_attitude_tests.find_by_test_id(params[:id])
    end
end

app/controllers/student/categories_controller.rb
class Student::CategoriesController < Student::StudentController
  before_action :set_data
  before_filter :authenticate_user!
  before_filter :check_plan, only: [:index]
  before_filter :user_is_admin?, except: [:index, :show]

  
  def index
    @categories = @course.categories.all

  end

  def new
    @category = Category.new
    render_js_only
  end

  def create
    @category = current_user.categories.create(category_params)
    if @category
      flash[:success] = "Category '#{@category.name}' has been created successfully"
    else
      flash[:danger] = "An error occured. Please try again."
    end
    redirect_to categories_path
  end

  def edit
    @category = Category.find_by_id(params[:id])
    render :new
  end

  def show
    @category = Category.includes(:sub_categories).find_by_id(params[:id])
    render_js_only
  end

  def update
    @category = Category.find_by_id(params[:id])
    @category.update(category_params) if @category
    render :show
  end

  def delete
    Category.find_by_id(params[:id]).destroy!
  end


  private

  def category_params
    params.require(:category).permit(:name)
  end

   def set_data
      @course = Course.find(params[:course_id])
    end

end

app/controllers/student/course_user_tests_controller.rb
class Student::CourseUserTestsController < Student::StudentController
  before_action :load_course_user_test, only: [:new, :update, :edit]
  before_action :set_course_user_test, only: [:update, :set_answers, :show, :edit]
  before_filter :check_plan, only: [:index]

  def new
    add_breadcrumb "Inicio", :root_path
    @course_user_test = CourseUserTest.new(course_user: @course_user, test: @test)
    @course_user_test.last_started = DateTime.now
    @course_user_test.time_left = @test.time_limit * 60
    if @course_user_test.save
      @course_user_test.test.questions.each do |q|
        @course_user_test.answers.create!(user: current_user, question: q)
      end
    else
      redirect_to student_course_tests_path(@course), notice: 'Ha ocurrido un error al guardar'
    end
  end

  def edit
    if !@course_user_test.completed?
      if @course_user_test.paused?
        @course_user_test.last_started = Time.at(Time.now)
      end
      @course_user_test.time_left -= (Time.now.to_i - @course_user_test.last_started.to_i)
      @course_user_test.time_left = 0 if @course_user_test.time_left < 0
      @course_user_test.time_completed = Time.at(Time.now) if @course_user_test.time_left == 0
      @course_user_test.status = @course_user_test.time_left <= 0 ? "completed" : "opened"
      @course_user_test.last_started = Time.at(Time.now)
      @course_user_test.save
      return redirect_to student_course_tests_path(@course), notice: 'El Test fue completado exitosamente.' if @course_user_test.time_left == 0
    end
  end

  def update
    respond_to do |format|
      if params["course_user_test"]['action_form'] == "end"
        final_questions = params["course_user_test"]["question_ids"].reject {|key,value| value == "marked" } if params["course_user_test"]["question_ids"]
        total_questions = @course_user_test.test.questions.count
        answered_questions = 0
        answered_questions = final_questions.count if final_questions
        percent_to_go = total_questions * 75/100
        if @course_user_test.save
          if ( @course_user_test.time_left - (Time.now.to_i - @course_user_test.last_started.to_i) ) > 0
            set_answers params["course_user_test"]["question_ids"] if params["course_user_test"]["question_ids"]
          else
            @course_user_test.status = "completed" # :completed
            @course_user_test.time_completed = DateTime.now
            @course_user_test.time_left = 0
            @course_user_test.save
            format.html { redirect_to student_course_tests_path(@course), notice: 'Lo siento, ¡el tiempo de ha consumido!, yus respuestas no han sido almacenadas, ahora este Test está completado.' }
            format.json { render :show, status: :created, location: student_course_tests_path(@course) }
          end
          if answered_questions >= percent_to_go
            @course_user_test.status = "completed" # :completed
            @course_user_test.time_completed = DateTime.now
            @course_user_test.time_left = 0
            @course_user_test.save
            format.html { redirect_to student_course_tests_path(@course), notice: 'Test was successfully completed.' }
            format.json { render :show, status: :created, location: student_course_tests_path(@course) }
          else
            format.html { redirect_to student_course_tests_path(@course), notice: 'Tus respuestas han sido almacenadas, pero para completar este test debes responder al menos el 75% del total de las preguntas.' }
            format.json { render :show, status: :created, location: student_course_tests_path(@course) }
          end
        else
          format.html { redirect_to new_student_course_test_course_user_test_path(@course,@test), notice: 'Ha ocurrido un error al guardar, verifique que ya no haya seleccionado este test' }
          format.json { render json: @course_user_test.errors, status: :unprocessable_entity }
        end
      end
      if params["course_user_test"]['action_form'] == "pause"
        set_answers params["course_user_test"]["question_ids"] if params["course_user_test"]["question_ids"]
        if @course_user_test.save
          format.html { redirect_to student_course_tests_path(@course), notice: 'El Test fue pausado exitosamente.' }
          format.json { render :show, status: :created, location: student_course_tests_path(@course) }
        end
      end
    end
  end

  private

    def set_answers answers
      answers.each do |q|
        marked = q[1] == "marked" ? 1 : 0
        if marked == 1
          @course_user_test.answers.where(user: current_user, question_id: q[0]).update_all(marked: 1)
        else
          @course_user_test.answers.where(user: current_user, question_id: q[0]).update_all(choice_id: q[1],marked: 0)
        end
      end
    end

    def load_course_user_test
      @course = Course.find(params[:course_id])
      @test = Test.find(params[:test_id])
      @course_user = CourseUser.where(course: @course, user: current_user).first if @course && @test
    end

    def set_course_user_test
      @course_user_test = CourseUserTest.where(course_user: @course_user, test: @test).first # :opened or :paused
    end

    def course_user_test_params
      params.require(:course_user_test).permit(:course_user_id, :test_id, :action_form, :question_ids => [])
    end
end

app/controllers/student/courses_controller.rb
class Student::CoursesController < Student::StudentController
  
  before_action :set_course, only: [:check_plan, :show]
  before_action :set_course_user, only: [:show]

  before_filter :check_plan, only: [:show]
  
  # GET /courses
  # GET /courses.json
  def index
    add_breadcrumb "Inicio", :root_path
    @courses = Course.preload(:tests,:categories => [:sub_categories => [:questions,:tutorials]] ).all
    @tests = Test.attitude
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    add_breadcrumb "Inicio", :root_path
    add_breadcrumb "Cursos ", student_courses_path
    @progress = @course_user.progress_percent
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    def set_course_user
      @course_user = course_user
    end

end

app/controllers/student/live_classes_controller.rb
class Student::LiveClassesController < Student::StudentController
  before_filter :check_plan, only: [:index]
  before_action :set_data

  def index
    @categories = Category.all
  end

  private

  def set_data
    @course = Course.find(params[:course_id])
  end

end

app/controllers/student/progress_controller.rb
class Student::ProgressController < Student::StudentController
  
  before_action :set_data
  before_filter :check_plan, only: [:index]
  
  # GET /progress
  # GET /progress.json
  def index
    add_breadcrumb "Inicio", :root_path
    add_breadcrumb "#{@course_user.course.name} ", student_course_path(@course_user.course)
  end

  private
    
    def set_data
      @course_user = CourseUser.where(course_id: params[:course_id], user: current_user).first
      @progress = @course_user.progress_percent
      @course = Course.find(params[:course_id])
    end
end

app/controllers/student/statistics_controller.rb
class Student::StatisticsController < Student::StudentController
  before_filter :check_plan, only: [:index]
  before_action :set_data

  def index
  	
  end

  private

  def set_data
    @course = Course.find(params[:course_id])
  end

end

app/controllers/student/student_controller.rb
class Student::StudentController < ApplicationController
  before_filter :authenticate_user!

  def check_plan
    # There must be a plan free first
    CourseUserPlan.create! course_user: course_user, plan: Plan.where(name: "Free").first if !course_user.course_user_plan.present? 
    # Redirigir a pagos si ha expirado el plan contratado del curso
    # raise course_user.course_user_plan.expiration_date.to_yaml
    if course_user.course_user_plan 
      if Date.today > course_user.course_user_plan.expiration_date
        cup = course_user.course_user_plan
        cup.status = "expired" # Marcar como expirado el plan
        cup.save
        ExpiredLicense.send_mail(course_user).deliver
        redirect_to payments_path
      else
        if (course_user.course_user_plan.expiration_date - Date.today).to_i <= 7
          cup = course_user.course_user_plan
          if cup.updated_at.strftime("%Y-%m-%d") != Date.today.strftime("%Y-%m-%d")
            RenewPlan.send_mail(course_user).deliver
          end
          cup.updated_at = Date.today
          cup.save
        end
      end
    end
  end

  # CUAL ES LA DIFERENCIA DE UN PLAN REGISTRADO Y UN PLAN PREMIUM?
  def redirect_if_premium_plan
    # Redirigir a pagos si no tiene plan registrado
    # return redirect_to payments_path if !course_user.course_user_plan.present?
    # Redirigir si no es un plan Premium
    # return redirect_to payments_path if course_user.plan.name != "Premium"
  end

  def course_user
    CourseUser.where(course: @course, user: current_user).first_or_create

    # cu = CourseUser.where(course: @course, user: current_user)
    # empty = cu.empty?
    # get_course_user = CourseUser.where(course: @course, user: current_user).first_or_create
    # if empty
    #   # TakingNewCourse.send_mail(get_course_user).deliver
    # end
    # return get_course_user
  end

  def update_tests_data
    course_user = CourseUser.where(course: @course, user: current_user).first if @course
    course_user_tests = CourseUserTest.where(course_user: course_user) if course_user
    cuts = course_user_tests
    cuts.where(status: 0).each { |r| 
                                  r.time_left = r.time_left - (Time.now.to_i - r.last_started.to_i)
                                  r.time_left = 0 if r.time_left < 0
                                  r.status = r.time_left == 0 ? 2 : 1
                                  r.last_started = Time.at(Time.now) if !r.completed?
                                  r.time_completed = Time.at(Time.now) if r.completed?
                                  r.save 
                                }
  end

end

app/helpers/student/course_test_user_helper.rb
module Student::CourseTestUserHelper
end

app/helpers/student/course_user_tests_helper.rb
module Student::CourseUserTestsHelper
end

app/helpers/student/video_classes_helper.rb
module Student::VideoClassesHelper
end

app/views/student/navigation/_vertical_navbar.html.erb
<nav  id="vertical-nav" >
  <ul id="main-links">
        <li class="nav-item">
          <a href="<%= student_course_path(@course) %>">
            <svg class="icon icon-home">
              <symbol id="icon-home" viewBox="0 0 32 32">
              <title>home</title>
              <path class="path1" d="M32 18.451l-16-12.42-16 12.42v-5.064l16-12.42 16 12.42zM28 18v12h-8v-8h-8v8h-8v-12l12-9z"></path>
              </symbol>
              <use xlink:href="#icon-home"></use>
              <span> Inicio </span>
            </svg>
          </a>
        </li>
        <li class="nav-item" >
          <a href="<%= student_course_progress_index_path(@course) %>"> 
            <svg class="icon icon-rocket"><symbol id="icon-rocket" viewBox="0 0 32 32">
              <title>rocket</title>
              <path class="path1" d="M22 2l-10 10h-6l-6 8c0 0 6.357-1.77 10.065-0.94l-10.065 12.94 13.184-10.255c1.839 4.208-1.184 10.255-1.184 10.255l8-6v-6l10-10 2-10-10 2z"></path>
              </symbol>
              <use xlink:href="#icon-rocket"></use>
            </svg>
            <span > Progreso </span>
          </a>
        </li>
        <li class="nav-item">
          <a href="<%= student_course_categories_path(@course) %>">
            <svg class="icon icon-book">
              <symbol id="icon-book" viewBox="0 0 32 32">
              <title>book</title>
              <path class="path1" d="M28 4v26h-21c-1.657 0-3-1.343-3-3s1.343-3 3-3h19v-24h-20c-2.2 0-4 1.8-4 4v24c0 2.2 1.8 4 4 4h24v-28h-2z"></path>
              <path class="path2" d="M7.002 26v0c-0.001 0-0.001 0-0.002 0-0.552 0-1 0.448-1 1s0.448 1 1 1c0.001 0 0.001-0 0.002-0v0h18.997v-2h-18.997z"></path>
              </symbol>
              <use xlink:href="#icon-book"></use>
              <span > Ejercicios </span>
            </svg>
          </a>
        </li>
        <li class="nav-item">
          <a href="<%= student_course_tutorials_path(@course) %>">
            <svg class="icon icon-books"><symbol id="icon-books" viewBox="0 0 36 32">
              <title>books</title>
              <path class="path1" d="M7 4h-6c-0.55 0-1 0.45-1 1v22c0 0.55 0.45 1 1 1h6c0.55 0 1-0.45 1-1v-22c0-0.55-0.45-1-1-1zM6 10h-4v-2h4v2z"></path>
              <path class="path2" d="M17 4h-6c-0.55 0-1 0.45-1 1v22c0 0.55 0.45 1 1 1h6c0.55 0 1-0.45 1-1v-22c0-0.55-0.45-1-1-1zM16 10h-4v-2h4v2z"></path>
              <path class="path3" d="M23.909 5.546l-5.358 2.7c-0.491 0.247-0.691 0.852-0.443 1.343l8.999 17.861c0.247 0.491 0.852 0.691 1.343 0.443l5.358-2.7c0.491-0.247 0.691-0.852 0.443-1.343l-8.999-17.861c-0.247-0.491-0.852-0.691-1.343-0.443z"></path>
              <path class="path4" d="M29 27c0 0.552-0.448 1-1 1s-1-0.448-1-1c0-0.552 0.448-1 1-1s1 0.448 1 1z"></path>
              </symbol>
              <use xlink:href="#icon-books"></use>
              <span > Tutoriales </span>
            </svg>
          </a>
        </li>
        <li class="nav-item">
          <a href="<%= student_course_tests_path(@course) %>">
              <svg class="icon icon-display"><symbol id="icon-display" viewBox="0 0 32 32">
              <title>display</title>
              <path class="path1" d="M0 2v20h32v-20h-32zM30 20h-28v-16h28v16zM21 24h-10l-1 4-2 2h16l-2-2z"></path>
              </symbol><use xlink:href="#icon-display"></use>
            </svg>
             <span > Simuladores </span>
          </a>
        </li>
        <li class="nav-item">
          <a href="<%= student_course_video_classes_path(@course) %>">
            <svg class="icon icon-play">
              <symbol id="icon-play" viewBox="0 0 32 32">
              <title>play</title>
              <path class="path1" d="M30.662 5.003c-4.488-0.645-9.448-1.003-14.662-1.003s-10.174 0.358-14.662 1.003c-0.86 3.366-1.338 7.086-1.338 10.997s0.477 7.63 1.338 10.997c4.489 0.645 9.448 1.003 14.662 1.003s10.174-0.358 14.662-1.003c0.86-3.366 1.338-7.086 1.338-10.997s-0.477-7.63-1.338-10.997zM12 22v-12l10 6-10 6z"></path>
              </symbol>
              <use xlink:href="#icon-play"></use>
              <span > Clases en Video </span>
            </svg>
          </a>
        </li>
        <li class="nav-item">
          <a href="<%=  student_course_statistics_path(@course) %>">
            <svg class="icon icon-stats-dots"><symbol id="icon-stats-dots" viewBox="0 0 32 32">
              <title>stats-dots</title>
              <path class="path1" d="M4 28h28v4h-32v-32h4zM9 26c-1.657 0-3-1.343-3-3s1.343-3 3-3c0.088 0 0.176 0.005 0.262 0.012l3.225-5.375c-0.307-0.471-0.487-1.033-0.487-1.638 0-1.657 1.343-3 3-3s3 1.343 3 3c0 0.604-0.179 1.167-0.487 1.638l3.225 5.375c0.086-0.007 0.174-0.012 0.262-0.012 0.067 0 0.133 0.003 0.198 0.007l5.324-9.316c-0.329-0.482-0.522-1.064-0.522-1.691 0-1.657 1.343-3 3-3s3 1.343 3 3c0 1.657-1.343 3-3 3-0.067 0-0.133-0.003-0.198-0.007l-5.324 9.316c0.329 0.481 0.522 1.064 0.522 1.691 0 1.657-1.343 3-3 3s-3-1.343-3-3c0-0.604 0.179-1.167 0.487-1.638l-3.225-5.375c-0.086 0.007-0.174 0.012-0.262 0.012s-0.176-0.005-0.262-0.012l-3.225 5.375c0.307 0.471 0.487 1.033 0.487 1.637 0 1.657-1.343 3-3 3z"></path>
              </symbol>
              <use xlink:href="#icon-stats-dots"></use>
            </svg>
            <span > Estadísticas </span>
          </a>
        </li> 
        <div class="nav-wrapper">
          <li class="nav-item">
            <a href="mailto:hola@aprendemy.com" >
              <svg class="icon icon-envelop"><symbol id="icon-envelop" viewBox="0 0 32 32">
                <title>envelop</title>
                <path class="path1" d="M29 4h-26c-1.65 0-3 1.35-3 3v20c0 1.65 1.35 3 3 3h26c1.65 0 3-1.35 3-3v-20c0-1.65-1.35-3-3-3zM12.461 17.199l-8.461 6.59v-15.676l8.461 9.086zM5.512 8h20.976l-10.488 7.875-10.488-7.875zM12.79 17.553l3.21 3.447 3.21-3.447 6.58 8.447h-19.579l6.58-8.447zM19.539 17.199l8.461-9.086v15.676l-8.461-6.59z"></path>
                </symbol>
                <use xlink:href="#icon-envelop"></use>
                <span > Soporte </span>
              </svg>
            </a>
          </li>
        </div>
  </ul>
</nav>