config/routes.rb
Rails.application.routes.draw do

  namespace :student do
    get 'video_classes/index'
  end

  namespace :student do
    get 'video_classes/show'
  end

  get 'webinar/index'


  resources :events
  
  namespace :backend do
    resources :blogs
    get '/dashboard' => 'dashboard#index', :as => 'dashboard'
    resources :attitude, only: [:index, :show, :update]
    # get '/attitude' => 'attitude#index', :as => 'attitude'
    # resources :sections
    # resources :tasks
    # resources :schools
    # resources :careers
    # resources :universities
  end

  get 'student/courses' => 'student/courses#index', as: :user_root
  
  namespace :student do

    # ATTITUDE TESTS
    # post '/attitude/process' => 'attitude#process', :as => 'attitude_process'
    resources :attitude_tests, :path => "attitude", only: [:index, :show, :update]
    # resources :attitude_tests, :path => "attitude", only: [:index, :show] do
      # resources :course_user_tests, :path => "test", only:[:edit, :new, :update]
    # end
    
    resources :courses, only: [:index, :show] do
      # root_path
      
      # TESTS
      resources :tests, only: [:index] do
        resources :course_user_tests, :path => "test", only:[:edit, :new, :update]
      end
      
      # PROGRESS
      resources :progress, only: [:index] do
        # RESOURCES
        resources :resources, only: [:show, :update]
      end
      # LIVE CLASSES
      get '/live_classes' => 'live_classes#index'

      # QUESTIONS
      resources :categories do
        resources :sub_categories do
          resources :answers, only:[:create]
        end
      end

      # TUTORIALS
      resources :tutorials

      #STATISTICS
      resources :statistics, only: [:index]

     # TUTORIALS
      resources :video_classes

    end
    
  end

  # PAYMENTS
  get 'pagos' => 'payments#index', as: :payments

  root 'home#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # USERS
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'users/registrations', sessions: 'users/sessions' }

  # get 'auth/facebook/callback', to: 'sessions#create'
  # get 'auth/failure', to: redirect('/')
  
  match '*unmatched_route', :to => 'application#raise_not_found!', via: :all
end

app/controllers/student/answers_controller.rb
class Student::AnswersController < Student::StudentController
  before_filter :check_plan, only: [:index]
  before_action :set_data

  def create
    respond_to do |format|
      if !current_user.answers.where(answer_params).any?
        @answer = current_user.answers.new(answer_params)
        @answer.item = nil
        if @answer.save
          format.html { redirect_to student_course_category_sub_category_path(@course,@category,@sub_category), notice: 'La respuesta fue creada exitosamente.' }
          format.json { render json: { "is_correct": @answer.is_correct?, "already_answered": false }, status: :created }
        else
          format.html { redirect_to student_course_category_sub_category_path(@course,@category,@sub_category), notice: 'La respuesta no pudo ser creada.' }
          format.json { render json: @answer.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to student_course_category_sub_category_path(@course,@category,@sub_category), notice: 'La respuesta ya fue creada.' }
        format.json { render json: { "is_correct": false, "already_answered": true }, status: :unprocessable_entity }
      end
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:question_id, :choice_id)
  end

  def set_data
    @category = Category.find(params[:category_id])
    @sub_category = SubCategory.find(params[:sub_category_id])
    @course = Course.find(params[:course_id])
  end

end

app/controllers/student/attitude_tests_controller.rb
class Student::AttitudeTestsController < Student::StudentController
  before_action :load_uat, only: [:show]
  # before_action :update_tests_data
  before_filter :check_plan, only: [:show]

  def index
  end

  def update
    uat = current_user.user_attitude_tests.find_by_test_id(params[:id])
    Answer.where(item: uat).destroy_all if !uat.blank?
    qs = vs = []
    qs = params['question_ids'].keys.map { |e| e } if params['question_ids']
    vs = params['question_ids'].values.map { |e| e } if params['question_ids']
    us = current_user.slice(:id)
    i = qs.map.with_index { |e, k| k }
    data = []
    i.each do |i|
      data[i] = { 
                  "question_id" => qs[i].to_i, 
                  "choice_id"   => vs[i].to_i,
                  "user_id"     => current_user.id,
                  "item_id"     => uat.id,
                  "item_type"   => "UserAttitudeTest"
                }

    end
    
    band = false

    if params['action_form'] == "end" && current_user.user_attitude_tests.find_by_test_id(params[:id]).test.questions.count == vs.count
      current_user.user_attitude_tests.find_by_test_id(params[:id]).update_attribute(:status,1)
      band = true
    end

    if Answer.create!(data) and !data.blank?
      if params['action_form'] == "pause" && current_user.user_attitude_tests.find_by_test_id(params[:id]).test.questions.count >= vs.count
        return redirect_to student_attitude_test_path(params['id']), notice: 'Test pausado correctamente, para finalizar un test debe contestar todas las preguntas' 
      end
      if band
        return redirect_to student_courses_path, notice: 'Hemos recibido tus pruebas de actitud, muy pronto recibiras tu resultados por email' 
      else
        return redirect_to student_courses_path, notice: 'Test pausado, para finalizar un test debe contestar todas las preguntas' 
      end
    else
      return redirect_to student_attitude_test_path(params['id']), alert: 'Ocurrió un error al actualizar este test'
    end
  end
  
  def show
  end
  
  private
    
    def load_uat
      current_user.user_attitude_tests.create!(test_id: params[:id]) unless current_user.user_attitude_tests.find_by_test_id(params[:id])
      @uat = current_user.user_attitude_tests.find_by_test_id(params[:id])
    end
end

app/controllers/student/categories_controller.rb
class Student::CategoriesController < Student::StudentController
  before_action :set_data
  before_filter :authenticate_user!
  before_filter :check_plan, only: [:index]
  before_filter :user_is_admin?, except: [:index, :show]

  
  def index
    @categories = @course.categories.all

  end

  def new
    @category = Category.new
    render_js_only
  end

  def create
    @category = current_user.categories.create(category_params)
    if @category
      flash[:success] = "Category '#{@category.name}' has been created successfully"
    else
      flash[:danger] = "An error occured. Please try again."
    end
    redirect_to categories_path
  end

  def edit
    @category = Category.find_by_id(params[:id])
    render :new
  end

  def show
    @category = Category.includes(:sub_categories).find_by_id(params[:id])
    render_js_only
  end

  def update
    @category = Category.find_by_id(params[:id])
    @category.update(category_params) if @category
    render :show
  end

  def delete
    Category.find_by_id(params[:id]).destroy!
  end


  private

  def category_params
    params.require(:category).permit(:name)
  end

   def set_data
      @course = Course.find(params[:course_id])
    end

end

app/controllers/student/course_user_tests_controller.rb
class Student::CourseUserTestsController < Student::StudentController
  before_action :load_course_user_test, only: [:new, :update, :edit]
  before_action :set_course_user_test, only: [:update, :set_answers, :show, :edit]
  before_filter :check_plan, only: [:index]

  def new
    add_breadcrumb "Inicio", :root_path
    @course_user_test = CourseUserTest.new(course_user: @course_user, test: @test)
    @course_user_test.last_started = DateTime.now
    @course_user_test.time_left = @test.time_limit * 60
    if @course_user_test.save
      @course_user_test.test.questions.each do |q|
        @course_user_test.answers.create!(user: current_user, question: q)
      end
    else
      redirect_to student_course_tests_path(@course), notice: 'Ha ocurrido un error al guardar'
    end
  end

  def edit
    if !@course_user_test.completed?
      if @course_user_test.paused?
        @course_user_test.last_started = Time.at(Time.now)
      end
      @course_user_test.time_left -= (Time.now.to_i - @course_user_test.last_started.to_i)
      @course_user_test.time_left = 0 if @course_user_test.time_left < 0
      @course_user_test.time_completed = Time.at(Time.now) if @course_user_test.time_left == 0
      @course_user_test.status = @course_user_test.time_left <= 0 ? "completed" : "opened"
      @course_user_test.last_started = Time.at(Time.now)
      @course_user_test.save
      return redirect_to student_course_tests_path(@course), notice: 'El Test fue completado exitosamente.' if @course_user_test.time_left == 0
    end
  end

  def update
    respond_to do |format|
      if params["course_user_test"]['action_form'] == "end"
        final_questions = params["course_user_test"]["question_ids"].reject {|key,value| value == "marked" } if params["course_user_test"]["question_ids"]
        total_questions = @course_user_test.test.questions.count
        answered_questions = 0
        answered_questions = final_questions.count if final_questions
        percent_to_go = total_questions * 75/100
        if @course_user_test.save
          if ( @course_user_test.time_left - (Time.now.to_i - @course_user_test.last_started.to_i) ) > 0
            set_answers params["course_user_test"]["question_ids"] if params["course_user_test"]["question_ids"]
          else
            @course_user_test.status = "completed" # :completed
            @course_user_test.time_completed = DateTime.now
            @course_user_test.time_left = 0
            @course_user_test.save
            format.html { redirect_to student_course_tests_path(@course), notice: 'Lo siento, ¡el tiempo de ha consumido!, yus respuestas no han sido almacenadas, ahora este Test está completado.' }
            format.json { render :show, status: :created, location: student_course_tests_path(@course) }
          end
          if answered_questions >= percent_to_go
            @course_user_test.status = "completed" # :completed
            @course_user_test.time_completed = DateTime.now
            @course_user_test.time_left = 0
            @course_user_test.save
            format.html { redirect_to student_course_tests_path(@course), notice: 'Test was successfully completed.' }
            format.json { render :show, status: :created, location: student_course_tests_path(@course) }
          else
            format.html { redirect_to student_course_tests_path(@course), notice: 'Tus respuestas han sido almacenadas, pero para completar este test debes responder al menos el 75% del total de las preguntas.' }
            format.json { render :show, status: :created, location: student_course_tests_path(@course) }
          end
        else
          format.html { redirect_to new_student_course_test_course_user_test_path(@course,@test), notice: 'Ha ocurrido un error al guardar, verifique que ya no haya seleccionado este test' }
          format.json { render json: @course_user_test.errors, status: :unprocessable_entity }
        end
      end
      if params["course_user_test"]['action_form'] == "pause"
        set_answers params["course_user_test"]["question_ids"] if params["course_user_test"]["question_ids"]
        if @course_user_test.save
          format.html { redirect_to student_course_tests_path(@course), notice: 'El Test fue pausado exitosamente.' }
          format.json { render :show, status: :created, location: student_course_tests_path(@course) }
        end
      end
    end
  end

  private

    def set_answers answers
      answers.each do |q|
        marked = q[1] == "marked" ? 1 : 0
        if marked == 1
          @course_user_test.answers.where(user: current_user, question_id: q[0]).update_all(marked: 1)
        else
          @course_user_test.answers.where(user: current_user, question_id: q[0]).update_all(choice_id: q[1],marked: 0)
        end
      end
    end

    def load_course_user_test
      @course = Course.find(params[:course_id])
      @test = Test.find(params[:test_id])
      @course_user = CourseUser.where(course: @course, user: current_user).first if @course && @test
    end

    def set_course_user_test
      @course_user_test = CourseUserTest.where(course_user: @course_user, test: @test).first # :opened or :paused
    end

    def course_user_test_params
      params.require(:course_user_test).permit(:course_user_id, :test_id, :action_form, :question_ids => [])
    end
end

app/controllers/student/courses_controller.rb
class Student::CoursesController < Student::StudentController
  
  before_action :set_course, only: [:check_plan, :show]
  before_action :set_course_user, only: [:show]

  before_filter :check_plan, only: [:show]
  
  # GET /courses
  # GET /courses.json
  def index
    add_breadcrumb "Inicio", :root_path
    @courses = Course.preload(:tests,:categories => [:sub_categories => [:questions,:tutorials]] ).all
    @tests = Test.attitude
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    add_breadcrumb "Inicio", :root_path
    add_breadcrumb "Cursos ", student_courses_path
    @progress = @course_user.progress_percent
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    def set_course_user
      @course_user = course_user
    end

end

app/controllers/student/live_classes_controller.rb
class Student::LiveClassesController < Student::StudentController
  before_filter :check_plan, only: [:index]
  before_action :set_data

  def index
    @categories = Category.all
  end

  private

  def set_data
    @course = Course.find(params[:course_id])
  end

end

app/controllers/student/progress_controller.rb
class Student::ProgressController < Student::StudentController
  
  before_action :set_data
  before_filter :check_plan, only: [:index]
  
  # GET /progress
  # GET /progress.json
  def index
    add_breadcrumb "Inicio", :root_path
    add_breadcrumb "#{@course_user.course.name} ", student_course_path(@course_user.course)
  end

  private
    
    def set_data
      @course_user = CourseUser.where(course_id: params[:course_id], user: current_user).first
      @progress = @course_user.progress_percent
      @course = Course.find(params[:course_id])
    end
end

app/controllers/student/statistics_controller.rb
class Student::StatisticsController < Student::StudentController
  before_filter :check_plan, only: [:index]
  before_action :set_data

  def index
  	
  end

  private

  def set_data
    @course = Course.find(params[:course_id])
  end

end

app/controllers/student/student_controller.rb
class Student::StudentController < ApplicationController
  before_filter :authenticate_user!

  def check_plan
    # There must be a plan free first
    CourseUserPlan.create! course_user: course_user, plan: Plan.where(name: "Free").first if !course_user.course_user_plan.present? 
    # Redirigir a pagos si ha expirado el plan contratado del curso
    # raise course_user.course_user_plan.expiration_date.to_yaml
    if course_user.course_user_plan 
      if Date.today > course_user.course_user_plan.expiration_date
        cup = course_user.course_user_plan
        cup.status = "expired" # Marcar como expirado el plan
        cup.save
        ExpiredLicense.send_mail(course_user).deliver
        redirect_to payments_path
      else
        if (course_user.course_user_plan.expiration_date - Date.today).to_i <= 7
          cup = course_user.course_user_plan
          if cup.updated_at.strftime("%Y-%m-%d") != Date.today.strftime("%Y-%m-%d")
            RenewPlan.send_mail(course_user).deliver
          end
          cup.updated_at = Date.today
          cup.save
        end
      end
    end
  end

  # CUAL ES LA DIFERENCIA DE UN PLAN REGISTRADO Y UN PLAN PREMIUM?
  def redirect_if_premium_plan
    # Redirigir a pagos si no tiene plan registrado
    # return redirect_to payments_path if !course_user.course_user_plan.present?
    # Redirigir si no es un plan Premium
    # return redirect_to payments_path if course_user.plan.name != "Premium"
  end

  def course_user
    CourseUser.where(course: @course, user: current_user).first_or_create

    # cu = CourseUser.where(course: @course, user: current_user)
    # empty = cu.empty?
    # get_course_user = CourseUser.where(course: @course, user: current_user).first_or_create
    # if empty
    #   # TakingNewCourse.send_mail(get_course_user).deliver
    # end
    # return get_course_user
  end

  def update_tests_data
    course_user = CourseUser.where(course: @course, user: current_user).first if @course
    course_user_tests = CourseUserTest.where(course_user: course_user) if course_user
    cuts = course_user_tests
    cuts.where(status: 0).each { |r| 
                                  r.time_left = r.time_left - (Time.now.to_i - r.last_started.to_i)
                                  r.time_left = 0 if r.time_left < 0
                                  r.status = r.time_left == 0 ? 2 : 1
                                  r.last_started = Time.at(Time.now) if !r.completed?
                                  r.time_completed = Time.at(Time.now) if r.completed?
                                  r.save 
                                }
  end

end

app/helpers/student/course_test_user_helper.rb
module Student::CourseTestUserHelper
end

app/helpers/student/course_user_tests_helper.rb
module Student::CourseUserTestsHelper
end

app/helpers/student/video_classes_helper.rb
module Student::VideoClassesHelper
end

app/views/student/progress/_no_curriculum.html.erb
<p style="margin-top: 50px; text-align: center; "> Este curso no tiene un curriculum por ahora. Vuelve Pronto </p>

app/views/student/progress/index.html.erb
<!-- Main Content -->
    <div id="application"> 
      <!-- Vertical Nav -->
      <%= render 'student/navigation/vertical_navbar' %>

      
      <div id="container">
        <div class="main-navigation">
          
            <div class="main-title-wrapper">
              <h1> Progreso</h1>
            </div>
              

            <div class="main-content-wrapper">
              <!-- Course Info -->
              <div class=" row rox-fix">
                <!-- Course Info -->
                <div class="col-sm-4 "> 
                  <div class="progress-course-img " style="background-image:  url('<%= @course.picture.url %>');" >
                  </div>
                  </div>
                  <div class="col-sm-8 progress-details" >
                  <h1><%= @course.name %> </h1>
                  <h3>Por <%= @course.author %></h3>

                  <p><%=  @course.description  %></p>

                  <p>Progreso en este curso: </p>
                  <div class="progress nav-progress-bar">
                    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="min-width: <%= @progress %>%;">
                      <%= @progress %> %
                    </div>

                    
                  </div>
                </div>
              </div>

              <h1 class="curriculum-title"> Curriculum </h1>

              <%= render 'no_curriculum' if @course.sections.empty? %>

              <!-- Curriculum -->
                <% 
                first = true 
                active = true 
                %>
                <% @course.sections.each do |section| %>
                  <div class="progress-wraper">                
                    <div class="progress-card">
                      <h1><%= section.name %></h1>
                    </div>

                    <div class="curriculum">
                      <ul>
                        <% section.resources.each do |resource| %>
                          <% go = active ? student_course_progress_resource_path(@course,@course.id,resource) : "" %>
                          <% completed = ResourceProgress.find_by(resource: resource, course_user: @course_user).completed? ? true : false if ResourceProgress.find_by(resource: resource, course_user: @course_user) %>
                          <li <%= "class='disabled'".html_safe if !active %>>
                            <%= link_to go do %>
                              <% if resource.material_type.downcase == 'video' %>
                                <div class="curriculum-type  <%= "disabled".html_safe if !active %>" >
                                  <i class="fa fa-play-circle-o <%=  resource.material_type.downcase %>" aria-hidden="true"></i>
                                </div>
                              <% elsif resource.material_type.downcase == 'blog' %>
                                <div class="curriculum-type <%= "disabled".html_safe if !active %>" >
                                  <i class="fa fa-file-text-o <%= resource.material_type.downcase %>" aria-hidden="true"></i>
                                </div>
                              <% else %>
                                <div class="curriculum-type <%= "disabled".html_safe if !active %>" >
                                  <i class="fa fa-question-circle-o <%=resource.material_type.downcase%>" aria-hidden="true"></i>
                                </div>
                              <% end %>

                              <div class="curriculum-item <%= "disabled".html_safe if !active %>">
                                <span><%= resource.name %></span>
                              </div>
                              <div class="curriculum-check <%= "disabled".html_safe if !active %>">
                                <i class="fa fa-check-circle-o progress-check" <%= 'style="color: #98ca3f !important"'.html_safe if completed %> aria-hidden="true"></i>
                              </div>   
                            <% end %>
                          </li>
                          <% if first && !completed
                              go = active == true ? student_course_progress_resource_path(@course,@course.id,resource) : "" 
                              active = true # cambiar a false si se quiere habilitar el bloqueo de progreso
                              first = false
                             end %>
                        <% end %>
                      </ul>
                    </div>
                  </div>
                <% end %>
            </div>
            
        </div>

      </div>
    </div>

<!-- // JQUERY animations an CSS changes$("#squarespaceModal").on('hidden.bs.modal', function (e) { -->
<script type="text/javascript">
  $(".progress-card").click(function(event) {
    $(this).parent().find(".curriculum").slideToggle(200);
  });
</script>



  